### ISSUE TITLE
Question about additional functions pthread

### ISSUE THREAD

**Issue by Jamaika1** [ultravideo/ThreadWrapper#1]
Hi
I'm interested in functions `pthread_key_create` `pthread_key_delete` `pthread_setspecific` `pthread_getspecific` and `pthread_self`.
Will they be added in the future?

Cheers

**Comment by fador** [comment]
Hi,

It seems like a relatively easy task, so I'll ask the maintainer @mikpit if he could add those.

**Comment by Jamaika1** [comment]
Thanks.
